/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package collageproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Vidula
 */
public class TaskGenerationForm extends javax.swing.JFrame {

    /**
     * Creates new form TaskGenerationForm
     */
    public TaskGenerationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_task = new javax.swing.JLabel();
        lbl_nametask = new javax.swing.JLabel();
        txt_nametsk = new javax.swing.JTextField();
        lbl_tsk_statement = new javax.swing.JLabel();
        txt_statement = new javax.swing.JTextField();
        lbl_noemp = new javax.swing.JLabel();
        spin_noemp = new javax.swing.JSpinner();
        lbl_workexp = new javax.swing.JLabel();
        txt_workexp = new javax.swing.JTextField();
        lbl_time = new javax.swing.JLabel();
        txt_time = new javax.swing.JTextField();
        btn_generate = new javax.swing.JButton();
        lbl_domain = new javax.swing.JLabel();
        txt_domain = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        lbl_task.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_task.setForeground(new java.awt.Color(255, 153, 0));
        lbl_task.setText("Task Generation Form");

        lbl_nametask.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_nametask.setForeground(new java.awt.Color(255, 153, 0));
        lbl_nametask.setText(" Name of Task");

        txt_nametsk.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        lbl_tsk_statement.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_tsk_statement.setForeground(new java.awt.Color(255, 153, 0));
        lbl_tsk_statement.setText("Task Statement");

        txt_statement.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        lbl_noemp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_noemp.setForeground(new java.awt.Color(255, 153, 0));
        lbl_noemp.setText("No of Employees");

        lbl_workexp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_workexp.setForeground(new java.awt.Color(255, 153, 0));
        lbl_workexp.setText("Min Work Experience");

        txt_workexp.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        lbl_time.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 153, 0));
        lbl_time.setText("Time Required");

        txt_time.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        btn_generate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btn_generate.setText("Generate Task");
        btn_generate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generateActionPerformed(evt);
            }
        });

        lbl_domain.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_domain.setForeground(new java.awt.Color(255, 153, 0));
        lbl_domain.setText("Domain of task");

        txt_domain.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(lbl_task))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_domain, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_domain, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_nametask, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_tsk_statement, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nametsk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_statement, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_noemp, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_workexp, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spin_noemp, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_workexp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(212, 212, 212)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lbl_task, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nametask, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nametsk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tsk_statement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_statement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_domain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_domain, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_noemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spin_noemp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_workexp, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txt_workexp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_time, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(btn_generate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu2.setText("Employee");

        jMenuItem1.setText("Employee Login");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Employee Registration Form");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_generateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generateActionPerformed
        // TODO add your handling code here:
        String path="jdbc:mysql://localhost:3306/employee";
        
        int no_of_emp_req=spin_noemp.getComponentCount();
        String domain=txt_domain.getText();
        int work_exp=Integer.parseInt(txt_workexp.getText());
        String querryempupdate;
        int emp_on_task[]=new int[no_of_emp_req];
       
        
        
        try
        {
           
           Connection con= DriverManager.getConnection(path,"root","root");
           Statement st=con.createStatement();
           ResultSet rs;
           
           String querryempavb="select * from employeedetails where e_doamin='"+domain+"' and e_workexperience>="+work_exp+";";
           
           rs=st.executeQuery(querryempavb);
           
            System.out.println("hello");
           
           if(rs.next())
           {
               for(int i=0;i<no_of_emp_req;i++)
               {
               emp_on_task[i]=rs.getInt("employee_id");
                   
               }
                      
           }
           /* 
           else
           {
               JOptionPane.showMessageDialog(null,"Invalid login credentials");
           }
           */
           
            
           for(int i=0;i<no_of_emp_req;i++)
           {
           querryempupdate="update employeedetails set e_isassigned=true where employee_id="+emp_on_task[i]+";";
            st.executeUpdate(querryempupdate);
           }
           System.out.println("hello");
       
           
            int task_temp=0;
           String querrytaskgen="insert into task (task_statement,task_domain,no_of_emp,min_we,time_req) values('"+txt_statement+"','"+domain+"',"+no_of_emp_req+","+work_exp+","+txt_time+");";
           rs=st.executeQuery(querrytaskgen);///problem is here 
           
           System.out.println("hello");
           
           if(rs.next())
           {
               task_temp=rs.getInt("task_id");
           }
           
           
           String querryupdater;
           
           for(int i=0;i<no_of_emp_req;i++)
           {
           querryupdater="update task set emp"+i+"_id="+emp_on_task[i]+" where task_id="+task_temp+";";
           st.executeUpdate(querryupdater);
           
           }
           
           System.out.println("hello");
          
           
           
           

        }
           catch(SQLException ex)
           {
               System.out.println("Exception Caught "+ex);
           }
        finally
        {
           //write code for finally here
        }
        
        
    }//GEN-LAST:event_btn_generateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskGenerationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskGenerationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskGenerationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskGenerationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskGenerationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generate;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_domain;
    private javax.swing.JLabel lbl_nametask;
    private javax.swing.JLabel lbl_noemp;
    private javax.swing.JLabel lbl_task;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JLabel lbl_tsk_statement;
    private javax.swing.JLabel lbl_workexp;
    private javax.swing.JSpinner spin_noemp;
    private javax.swing.JTextField txt_domain;
    private javax.swing.JTextField txt_nametsk;
    private javax.swing.JTextField txt_statement;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_workexp;
    // End of variables declaration//GEN-END:variables
}
